package hue.captains.singapura.js.homing.studio.base;

import hue.captains.singapura.js.homing.core.*;
import hue.captains.singapura.js.homing.server.EmptyParam;
import hue.captains.singapura.js.homing.server.EsModuleGetAction;
import hue.captains.singapura.js.homing.server.ModuleQuery;
import hue.captains.singapura.js.homing.server.QueryParamResolver;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verifies the full Doc-proxy serving path:
 *   1. A DocGroup defines typed Docs in Java (in studio-base, not core)
 *   2. EsModuleGetAction (in homing-server) dispatches via the generic SelfContent interface
 *   3. The served JS body contains the auto-emitted const declarations
 *   4. ExportWriter adds the trailing export block
 *   5. Consumers that import any Doc get DocManager auto-injected via the generic
 *      ManagerInjector mechanism — no homing-server-side knowledge of DocGroup
 */
class DocGroupServingTest {

    private final EsModuleGetAction action = new EsModuleGetAction(new QueryParamResolver());

    public record TestDocs() implements DocGroup<TestDocs> {
        public static final TestDocs INSTANCE = new TestDocs();

        public record FirstDoc() implements Doc<TestDocs> {
            @Override public String path()     { return "homing/md/test/first.md"; }
            @Override public String title()    { return "First Doc"; }
            @Override public String summary()  { return "Summary one"; }
            @Override public String category() { return "TEST"; }
        }

        public record SecondDoc() implements Doc<TestDocs> {
            @Override public String path()     { return "homing/md/test/second.md"; }
            @Override public String title()    { return "Second \"quoted\" Doc"; }   // verifies escaping
            @Override public String summary()  { return ""; }
            @Override public String category() { return "TEST"; }
        }

        @Override public List<Doc<TestDocs>> docs() {
            return List.of(new FirstDoc(), new SecondDoc());
        }
    }

    @Test
    void docGroup_servesAutoGeneratedJsBody() throws Exception {
        var query = new ModuleQuery(TestDocs.class.getName());   // binary name (handles nested $)
        var result = action.execute(query, new EmptyParam.NoHeaders()).get();
        String js = result.body();

        // 1. Imports the runtime DocManager
        assertTrue(js.contains("import { DocManagerInstance as _docs }"),
                "DocGroup body should import DocManager runtime");

        // 2. One const-declaration per Doc, with metadata baked in
        assertTrue(js.contains("const FirstDoc = _docs.doc(\"homing/md/test/first.md\", \"First Doc\""),
                "Should declare FirstDoc with its path and title");
        assertTrue(js.contains("\"Summary one\""),
                "Should include summary string");
        assertTrue(js.contains("\"TEST\""),
                "Should include category string");

        // 3. JSON escaping handles embedded quotes
        assertTrue(js.contains("\"Second \\\"quoted\\\" Doc\""),
                "Should escape embedded quotes in metadata: " + js);

        // 4. ExportWriter adds the export block
        assertTrue(js.contains("export {"),
                "Should append export block from ExportsOf");
        assertTrue(js.contains("FirstDoc"),
                "Export block should include FirstDoc");
        assertTrue(js.contains("SecondDoc"),
                "Export block should include SecondDoc");
    }

    /** A consumer module that imports a Doc — should auto-receive `import { DocManagerInstance as docs }`. */
    public record TestConsumer() implements EsModule<TestConsumer> {
        public static final TestConsumer INSTANCE = new TestConsumer();

        @Override public ImportsFor<TestConsumer> imports() {
            return ImportsFor.<TestConsumer>builder()
                    .add(new ModuleImports<>(List.of(new TestDocs.FirstDoc()), TestDocs.INSTANCE))
                    .build();
        }

        @Override public ExportsOf<TestConsumer> exports() {
            return new ExportsOf<>(INSTANCE, List.of());
        }
    }

    @Test
    void collectManagerInjectors_findsDocGroupViaGenericInterface() {
        // Generic check: TestDocs is a ManagerInjector via DocGroup's default methods.
        // EsModuleGetAction has no compile-time knowledge of DocGroup itself —
        // the marker interface is the only contract.
        List<ManagerInjector> injectors = EsModuleGetAction.collectManagerInjectors(TestConsumer.INSTANCE);

        assertEquals(1, injectors.size(),
                "Should find exactly one ManagerInjector reachable from TestConsumer");
        var mi = injectors.get(0);
        assertEquals("docs", mi.managerBindName(),
                "DocGroup binds its manager as 'docs' in consumer code");
        assertEquals("DocManagerInstance", mi.managerExportName(),
                "The exported runtime symbol is DocManagerInstance");
        assertSame(DocManager.INSTANCE, mi.manager(),
                "The injected manager must be DocManager.INSTANCE");
    }
}
