package hue.captains.singapura.js.homing.studio;

import hue.captains.singapura.js.homing.studio.base.DocRegistry;
import hue.captains.singapura.js.homing.studio.base.app.CatalogueRegistry;
import hue.captains.singapura.js.homing.studio.base.app.StudioBrand;
import hue.captains.singapura.js.homing.studio.es.BuildingBlocksCatalogue;
import hue.captains.singapura.js.homing.studio.es.DocBrowser;
import hue.captains.singapura.js.homing.studio.es.DoctrineCatalogue;
import hue.captains.singapura.js.homing.studio.es.ArchitectureRfcsCatalogue;
import hue.captains.singapura.js.homing.studio.es.ContentRfcsCatalogue;
import hue.captains.singapura.js.homing.studio.es.JourneysCatalogue;
import hue.captains.singapura.js.homing.studio.es.OperationsJourneysCatalogue;
import hue.captains.singapura.js.homing.studio.es.ReleasesCatalogue;
import hue.captains.singapura.js.homing.studio.es.RfcJourneysCatalogue;
import hue.captains.singapura.js.homing.studio.es.RfcsCatalogue;
import hue.captains.singapura.js.homing.studio.es.VisualSystemRfcsCatalogue;
import hue.captains.singapura.js.homing.studio.es.StudioCatalogue;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

/**
 * RFC 0005 §3 — single conformance test for the catalogue tree. Constructs the
 * {@link CatalogueRegistry} from the studio's explicit catalogue list. The four
 * boot-time validations (strict tree, no cycles, closure completeness, doc
 * reachability) are mechanically enforced by the constructor; this test pins
 * registry construction success in CI.
 *
 * <p>Per D10, no per-Catalogue dynamic test factory — there's no manual JS in
 * the catalogue stack at all (auto-generated by {@code CatalogueAppHost} using
 * the shared renderer). Boot-time fail-fast is the only failure surface; this
 * test is the gate.</p>
 */
class StudioCatalogueConstructsTest {

    @Test
    void catalogueRegistryConstructsCleanly() {
        // Mirror StudioServer.main's catalogue closure exactly, so this test fails
        // at the same moment a real boot would fail.
        var brand = new StudioBrand("Homing · studio", StudioCatalogue.class);

        // Build the doc registry the same way StudioBootstrap does — from the studio's
        // doc providers (the catalogue side + DocBrowser).
        var docRegistry = new DocRegistry(java.util.stream.Stream.of(
                        DocBrowser.INSTANCE.docs(),
                        BuildingBlocksCatalogue.INSTANCE.docs(),
                        ReleasesCatalogue.INSTANCE.docs())
                .flatMap(List::stream)
                .toList());

        var catalogues = List.of(
                StudioCatalogue.INSTANCE,
                DoctrineCatalogue.INSTANCE,
                RfcsCatalogue.INSTANCE,
                ArchitectureRfcsCatalogue.INSTANCE,
                ContentRfcsCatalogue.INSTANCE,
                VisualSystemRfcsCatalogue.INSTANCE,
                JourneysCatalogue.INSTANCE,
                RfcJourneysCatalogue.INSTANCE,
                OperationsJourneysCatalogue.INSTANCE,
                BuildingBlocksCatalogue.INSTANCE,
                ReleasesCatalogue.INSTANCE
        );

        assertDoesNotThrow(() -> new CatalogueRegistry(brand, docRegistry, catalogues));
    }
}
