// =============================================================================
// PlanRenderer — shared renderer for any Plan tracker.
//
// renderPlan({ data, nav, brand })  → Node  (index page)
// renderStep({ data, nav, brand, phaseId }) → Node  (detail page for one phase)
//
// `data` matches the Plan interface (kicker, title, subtitle, totalProgress,
//        openDecisions, executionDoc?, dossierDoc?, phases[], decisions[]).
// `nav` provides URL builders the renderer needs:
//        { home, journeys, step(phaseId), docReader(path), self }
// `brand` is { href, label } for the studio header.
//
// Doctrine note: PlanRenderer is the framework's view-construction code; it
// uses createElement freely and is what consumer code (auto-generated by
// PlanAppModule) calls into. Consumer JS itself contains no DOM authoring.
// =============================================================================

// `href` is normally auto-injected for AppLink-importing modules. PlanRenderer
// has no AppLinks (it's a generic helper); alias from the explicit
// HrefManagerInstance import declared in PlanRenderer.java.
var href = HrefManagerInstance;

function _docLink(navDocReader, path, label) {
    var a = document.createElement("a");
    href.set(a, navDocReader(path));
    a.textContent = label;
    return a;
}

// ---- index page ----
function renderPlan(props) {
    var data = props.data;
    var nav  = props.nav;
    var brand = props.brand;

    var root = document.createElement("div");
    css.addClass(root, st_root);

    root.appendChild(Header({
        brand:  brand,
        crumbs: [
            { text: "Home",     href: nav.home },
            { text: "Journeys", href: nav.journeys },
            { text: data.title }
        ]
    }));

    var main = document.createElement("div");
    css.addClass(main, st_main);

    var kicker = document.createElement("div");
    css.addClass(kicker, st_kicker);
    kicker.textContent = data.kicker;
    main.appendChild(kicker);

    var title = document.createElement("h1");
    css.addClass(title, st_title);
    title.textContent = data.title;
    main.appendChild(title);

    var subtitle = document.createElement("p");
    css.addClass(subtitle, st_subtitle);
    subtitle.textContent = data.subtitle;
    main.appendChild(subtitle);

    main.appendChild(OverallProgress({
        caption: "Overall",
        summary: data.phases.length + " phases · " + data.openDecisions + " open decisions",
        percent: data.totalProgress
    }));

    if (data.decisions && data.decisions.length > 0) {
        var decisionCards = data.decisions.map(function(d) {
            return DecisionCard({
                id:             d.id,
                question:       d.question,
                recommendation: d.recommendation,
                rationale:      d.rationale,
                chosen:         d.chosenValue,
                statusSlug:     d.statusSlug,
                statusLabel:    d.statusLabel
            });
        });
        main.appendChild(Section({
            title:     "Open decisions",
            children:  decisionCards,
            gridless:  true
        }));
    }

    var stepCards = data.phases.map(function(p) {
        var doneCount  = (p.tasks || []).filter(function(t) { return t.done; }).length;
        var totalCount = (p.tasks || []).length;
        return StepCard({
            href:        nav.step(p.id),
            idLabel:     "PHASE " + p.id,
            title:       p.label,
            summary:     p.summary,
            statusSlug:  p.statusSlug,
            statusLabel: p.statusLabel,
            progress:    p.progress,
            doneCount:   doneCount,
            totalCount:  totalCount,
            effort:      p.effort
        });
    });
    main.appendChild(Section({
        title:    "Phases",
        children: stepCards,
        gridless: true
    }));

    // Footer — optional doc links + raw-data hint.
    var footerChildren = [];
    if (data.executionDoc) {
        footerChildren.push("References: ");
        footerChildren.push(_docLink(nav.docReader, data.executionDoc, "Execution Plan (prose)"));
    }
    if (data.dossierDoc) {
        footerChildren.push(" · ");
        footerChildren.push(_docLink(nav.docReader, data.dossierDoc, "Dossier (decision context)"));
    }
    if (footerChildren.length > 0) {
        main.appendChild(Footer({ children: footerChildren }));
    }

    root.appendChild(main);
    return root;
}

// ---- detail page ----
function renderStep(props) {
    var data    = props.data;
    var nav     = props.nav;
    var brand   = props.brand;
    var phaseId = props.phaseId;

    var phase = null;
    for (var i = 0; i < data.phases.length; i++) {
        if (data.phases[i].id === phaseId) { phase = data.phases[i]; break; }
    }

    var root = document.createElement("div");
    css.addClass(root, st_root);

    var crumbs = [
        { text: "Home",     href: nav.home },
        { text: "Journeys", href: nav.journeys },
        { text: data.title, href: nav.self }
    ];
    if (phase) crumbs.push({ text: "Phase " + phase.id });
    else crumbs.push({ text: "(phase not found)" });

    root.appendChild(Header({ brand: brand, crumbs: crumbs }));

    var main = document.createElement("div");
    css.addClass(main, st_main);

    if (!phase) {
        var err = document.createElement("p");
        css.addClass(err, st_subtitle);
        err.textContent = "No phase with id " + JSON.stringify(phaseId) + ".";
        main.appendChild(err);
        root.appendChild(main);
        return root;
    }

    var kicker = document.createElement("div");
    css.addClass(kicker, st_kicker);
    kicker.textContent = "PHASE " + phase.id;
    main.appendChild(kicker);

    var title = document.createElement("h1");
    css.addClass(title, st_title);
    title.textContent = phase.label;
    main.appendChild(title);

    var subtitle = document.createElement("p");
    css.addClass(subtitle, st_subtitle);
    subtitle.textContent = phase.summary;
    main.appendChild(subtitle);

    // Status row: badge + effort + progress.
    var statusRow = document.createElement("div");
    statusRow.style.cssText = "display:flex; align-items:center; gap:12px; margin-bottom:18px;";
    statusRow.appendChild(StatusBadge({ statusSlug: phase.statusSlug, statusLabel: phase.statusLabel }));
    if (phase.effort) {
        var eff = document.createElement("span");
        eff.style.cssText = "font-size:13px;color:var(--st-gray-mid);";
        eff.textContent = "Effort: " + phase.effort;
        statusRow.appendChild(eff);
    }
    var progSpan = document.createElement("span");
    progSpan.style.cssText = "font-size:13px;color:var(--st-gray-mid);";
    progSpan.textContent = (phase.progress || 0) + "%";
    statusRow.appendChild(progSpan);
    main.appendChild(statusRow);

    // Description (prose) — optional.
    if (phase.description) {
        var desc = document.createElement("p");
        desc.style.cssText = "margin:0 0 18px 0;";
        desc.textContent = phase.description;
        main.appendChild(desc);
    }

    // Tasks panel.
    if (phase.tasks && phase.tasks.length > 0) {
        main.appendChild(Panel({
            title:    "Tasks",
            children: [TodoList({ tasks: phase.tasks })]
        }));
    }

    // Metrics panel — before/after measurements per phase. Hidden when the
    // phase has no metrics (most common case). Used by cleanup / refactor /
    // migration plans where the value is the quantitative delta.
    if (phase.metrics && phase.metrics.length > 0) {
        main.appendChild(Panel({
            title:    "Metrics",
            children: [MetricsTable({ rows: phase.metrics })]
        }));
    }

    // Dependencies panel.
    if (phase.dependsOn && phase.dependsOn.length > 0) {
        var depItems = phase.dependsOn.map(function(d) {
            var li = document.createElement("li");
            var a = document.createElement("a");
            href.set(a, nav.step(d.phaseId));
            a.textContent = "Phase " + d.phaseId;
            li.appendChild(a);
            li.appendChild(document.createTextNode(" — " + d.reason));
            return li;
        });
        var ul = document.createElement("ul");
        ul.style.cssText = "margin:0; padding-left:1.4em;";
        for (var di = 0; di < depItems.length; di++) ul.appendChild(depItems[di]);
        main.appendChild(Panel({ title: "Depends on", children: [ul] }));
    }

    // Verification + Rollback + Notes — single-line panels.
    if (phase.verification) {
        var v = document.createElement("p");
        v.style.cssText = "margin:0;";
        v.textContent = phase.verification;
        main.appendChild(Panel({ title: "Verification gate", children: [v] }));
    }
    if (phase.rollback) {
        var r = document.createElement("p");
        r.style.cssText = "margin:0;";
        r.textContent = phase.rollback;
        main.appendChild(Panel({ title: "Rollback", children: [r] }));
    }
    if (phase.notes) {
        var n = document.createElement("p");
        n.style.cssText = "margin:0; color:var(--st-gray-mid); font-style:italic;";
        n.textContent = phase.notes;
        main.appendChild(Panel({ title: "Notes", children: [n] }));
    }

    // Prev / Next nav at bottom.
    var idx = data.phases.indexOf(phase);
    var navRow = document.createElement("div");
    navRow.style.cssText = "display:flex; justify-content:space-between; margin-top:24px;";
    if (idx > 0) {
        var prev = document.createElement("a");
        href.set(prev, nav.step(data.phases[idx - 1].id));
        prev.textContent = "← Phase " + data.phases[idx - 1].id;
        navRow.appendChild(prev);
    } else {
        navRow.appendChild(document.createElement("span"));
    }
    if (idx < data.phases.length - 1) {
        var next = document.createElement("a");
        href.set(next, nav.step(data.phases[idx + 1].id));
        next.textContent = "Phase " + data.phases[idx + 1].id + " →";
        navRow.appendChild(next);
    }
    main.appendChild(navRow);

    root.appendChild(main);
    return root;
}
